### ISSUE TITLE
RabbitMQ does not use authentication user/password

### ISSUE THREAD

**Issue by huber-and** [groundhog2k/helm-charts#1197]
It looks like the RabbitMQ chart does ignore the authentication settings.
When set env.RABBITMQ_DEFAULT_USER and env.RABBITMQ_DEFAULT_PASS it works as expected.

**Comment by groundhog2k** [comment]
How did you test?
As described in Readme and also values.yaml the authentication.user & authentication.password are only for the initial admin user. If you change that in the Rabbit management UI the values are ignored on further upgrade deployments.

This is how I tested it
```
# Ingress
...
...

# Default user and erlang cookie
authentication:
  ## Initial user name
  user: "iamadmin"

  ## Initial password
  password: "secret"

  ## Erlang cookie (MANDATORY)
  erlangCookie: "VGhpc0lzTXlFcmxhbmdDb29raWUK"

## Management UI plugin options
managementPlugin:
  ## Enable management UI plugin with default configuration
  enabled: true

## Storage parameters
storage:
  requestedSize: 256Mi
```

Afterwards you can login with "iamadmin"/"secret".
