### ISSUE TITLE
[rabbitmq] Feature flags not being picked up

### ISSUE THREAD

**Issue by WyriHaximus** [groundhog2k/helm-charts#1253]
Giving the warning on the chart to enable feature flags, I've tried through the chart with the following configuration but they are not being picked up. Am I doing something wrong?

```yaml
replicaCount: 3
env:
  - name: "RABBITMQ_FEATURE_FLAGS"
    value: "quorum_queue"
```
