### ISSUE TITLE
Web ask for user/password

### ISSUE THREAD

**Issue by rackoot** [groundhog2k/helm-charts#1255]
After install rabbitmq, web access is asking for username and password twice.

I've set up username and password for rabbitmq, but it doesn't work. User guest/guest does not work either.

<img width="1080" alt="image" src="https://github.com/groundhog2k/helm-charts/assets/116320717/25c1dcf1-764d-454f-b19e-67e354bdcd8e">

**Comment by groundhog2k** [comment]
I tried it with following values.yaml on my test cluster at it definitely works:
```
replicaCount: 3

## Ingress configuration
ingress:
  enabled: true

  ## Additional ingress annotations
  annotations:
    cert-manager.io/cluster-issuer: local-ca

  ## Hosts
  hosts:
    - host: rabbit.k8s.local
      paths:
        - /
  tls:
    - hosts:
        - "rabbit.k8s.local"
      secretName: rabbit-k8s-local 

customConfig: |
  cluster_partition_handling = autoheal
  queue_master_locator = min-masters
  log.console = true
  log.console.level = info
  log.console.use_colors = off

# Default user and erlang cookie
# The erlang cookie is important for clustered or container based usage
# Find more information about it at https://hub.docker.com/_/rabbitmq and https://www.rabbitmq.com/clustering.html#erlang-cookie
# The erlang cookie is a MANDATORY VALUE
# Alternative is to set the environment variable ERLANG_COOKIE
authentication:
  ## Initial user name
  user: "guest"

  ## Initial password
  password: "guest"

  ## Erlang cookie (MANDATORY)
  erlangCookie: "sdkjferktjnkjr4t34jk5345345345srdgdfgh46ergezt435zte5rg"

## K8s peer discovery plugin options
k8sPeerDiscoveryPlugin:
  ## Enable K8s peer discovery plugin for a RabbitMQ HA-cluster with default configuration
  enabled: true

## Prometheus plugin options
prometheusPlugin:
  ## Enable prometheus monitoring plugin with default configuration
  enabled: true

## Common (recommended) cluster settings
clustering:
  ## Force boot in case cluster peers are not available
  forceBoot: true

## Storage parameters
storage:
  ## Alternative set requestedSize to define a size for a dynamically created PVC
  requestedSize: 128Mi

  ## the storage class name
  # className: "nfs-storage"

```

Please check your values.yaml config and try again.
