### ISSUE TITLE
[graylog] README is not describing the whole setup?

### ISSUE THREAD

**Issue by kastl-ars** [groundhog2k/helm-charts#1384]
Hi Göran,

I am currently playing with Graylog and thus found your chart and am currently testing it. Thanks for taking the time to create and maintain a chart. I know how much work that can be.

I found some issues, not sure if I am misunderstand something or the chart's documentation needs more details.

1. I noticed the README is a little sparse, or in other words, wrong. :-)

```
helm install my-release groundhog2k/graylog
```

This command will not install all of the necessary components, if I understand the chart correctly. No mongodb is being installed, no elasticsearch, etc. If using external components, one would need to provide things like host, username, passwords, so at least a `values.yaml` is needed.

2. I could not get mongodb deployed as a sub-chart / dependency, the pod was running but connections from graylog always failed. The user `graylog` could not authenticate, using the `graylog` database.

I used the following settings in my `values.yaml`:

```
mongodb:
  enabled: true
  settings: 
    rootUsername: admin
    rootPassword: totallynotsecure
  userDatabase:
    name: graylog
    user: graylog
    password: anothertotallynotsecurepassword
```

Do I need something else to get this working? Or is this an error in the mongodb chart?

3. Using a separate MongoDB I get one step further, but now no OpenSearch/ElasticSearch is found. The chart's `values.yaml` does not contain any hints on that other than the three lines in the settings:

https://github.com/groundhog2k/helm-charts/blob/master/charts/graylog/values.yaml#L255

Using localhost sounds like it should be running in the same pod?

IMHO this is something that should be described in the README.

Kind Regards,
Johannes

**Comment by groundhog2k** [comment]
Hi @kastl-ars ,
first of all, I updated the chart a few minutes ago, to use the latest MongoDB version 7.x.
To make sure it works, I tried the following exmaple configuration for testing on my local environment:
(Here in the example, I added Ingress using my local cert issuer - you can ignore that)

```
## Ingress configuration
ingress:
  ## Enable ingress endpoint
  enabled: true
  ## Additional ingress annotations
  annotations:
    cert-manager.io/cluster-issuer: local-ca
  ## Hosts
  hosts:
    - host: graylog.k8s.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  ## TLS settings for hosts
  tls:
    - secretName: graylog-k8s-local
      hosts:
       - graylog.k8s.local

## Graylog specific settings
settings:
  http:
    externalUri: "https://graylog.k8s.local/"

  javaOpts:
  passwordSecret: "somepasswordpepper"

  rootUser:
    username: "admin"
    # echo -n admin | shasum -a 256
    sha2Password: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    email: ""
    timezone: "UTC"

  journal:
    maxAge: "12h"
    maxSize: "5gb"

  elastic:
    hosts: "http://YOUR-OPENSEARCH-SERVICE:9200"
    indexPrefix: "graylog"

## Storage parameters for Graylog journal
storage:
  requestedSize: 6Gi

## MongoDB configuration
mongodb:
  ## Enable MongoDB helm chart for deployment (default: false)
  enabled: true

  ## Database settings
  settings:
    ## The root username (default: admin)
    rootUsername: "admin"
    ## The root user password
    rootPassword: "admin"

  ## Optional user database which is created during first startup with user and password
  userDatabase:
    name: "graylogdb"
    ## Database user
    user: "test"
    ## Database password
    password: "test"
```

You have to deploy OpenSearch/Elasticsearch using their helm charts and point the elastic.host: configuration (see above) to the service endpoint of your OpenSearch/ElasticSearch deployment. (f.e.; https://opensearch-project.github.io/helm-charts/ )
