### ISSUE TITLE
Error when using keySecretName in replicaSet with Mongo Chart

### ISSUE THREAD

**Issue by thuanpham582002** [groundhog2k/helm-charts#1385]
I encountered an error when using keySecretName:  
```json
{"error":{"code":30,"codeName":"InvalidPath","errmsg":"permissions on /replicaset/keyfile are too open"}}
```

Here is my config:
```yaml
replicaSet:
  enabled: true  # Enables replica set deployment mode
  name: "repl"  # Replica set name
  key: {}  # Internal replica set authentication key (base64 encoded string 6-1024 chars)
  keySecretName: "mongodb-keyfile-secret"  # Existing secret with a "keyfile" containing the base64 encoded key string
``` 

I am sure I created mongodb-keyfile-secret.
