### ISSUE TITLE
MariaDB chart overwrites passwords in secrets when upgrading release

### ISSUE THREAD

**Issue by nikkoura** [groundhog2k/helm-charts#183]
When upgrading a release, if the values passed to helm specify that a root password should be randomly generated, the password stored in the release Secret is overwritten with a new random value. Same thing goes for the user database password.
The passwords used by the database are then lost.

Random password generation should only happen if there is no corresponding value present in the existing Secret.

**Comment by groundhog2k** [comment]
@nikkoura : Thank you for the PR - I will review it and also check the impact in combination with other charts (like Nextcloud / Gitea) when Mariadb is a dependent chart. I think in the latter case some additional logic is needed in the other charts.

**Comment by nikkoura** [comment]
My understanding of your charts was that using mariadb/postgresql/etc as subcharts would imply specifying all of the DB configuration in the main chart: database name, username, password... But I may be wrong.

One way to avoid this issue with subcharts is not to replicate secrets between application and database, but to have the application directly use the database secret to get its credentials. But this may have implications for charts already deployed in the field.

**Comment by groundhog2k** [comment]
The answer is "Yes and no" :-) Take a look at the Nextcloud chart, for example. To make the deployment very easy I decided to use the database, username and password etc. from the MariaDB chart values also for Nextcloud when the internal (dependent) MariaDB chart is used (mariadb.enabled = true).
To keep that "easy-to-use" approach. Your logic needs to be copied to the other charts or by using a clever helper template.

**Comment by groundhog2k** [comment]
@nikkoura - merged :-) Sorry.. It took a while because of my daily job.
I will use this approach to upgrade all other charts too.
Thank you!

**Comment by nikkoura** [comment]
No worries :)
May I help by preparing the corresponding PR for other charts? Let me know if interested (I understand that reviewing and testing can be longer than doing the job in that kind of case) and which charts I could help you with.

**Comment by nikkoura** [comment]
> The answer is "Yes and no" :-) Take a look at the Nextcloud chart, for example. To make the deployment very easy I decided to use the database, username and password etc. from the MariaDB chart values also for Nextcloud when the internal (dependent) MariaDB chart is used (mariadb.enabled = true).

I *think* we mean the same thing, but just to make sure: what I meant is that for charts such as Nextcloud:

**If you run this, everything will work fine:**
```shell
helm install nextcloud groundhog2k/nextcloud \
   --set=mariadb.enabled=true \
   --set=mariadb.userDatabase.name=nextcloud \
   --set=mariadb.userDatabase.user=nextcloud \
   --set=mariadb.userDatabase.password=terrible_pwd
```
Templated secrets:
```yaml
---
# Source: nextcloud/charts/mariadb/templates/secureconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mariadb
  labels:
    helm.sh/chart: mariadb-0.2.5
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "10.5.8"
    app.kubernetes.io/managed-by: Helm
stringData:
  MYSQL_ROOT_PASSWORD: oy26ZaHTcy
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_PASSWORD: terrible_pwd
---
# Source: nextcloud/templates/secureconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  labels:
    helm.sh/chart: nextcloud-0.3.8
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "20.0.4-apache"
    app.kubernetes.io/managed-by: Helm
stringData:
  MYSQL_HOST: nextcloud-mariadb
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_PASSWORD: terrible_pwd
---
```
**However, if you want to make use of a randomly-generated password for the mariadb chart, you will probably not have something functional.**

Running this:
```shell
helm install nextcloud groundhog2k/nextcloud \
   --set=mariadb.enabled=true \
   --set=mariadb.userDatabase.name=nextcloud \
   --set=mariadb.userDatabase.user=nextcloud
```
will result in this template for the secrets:

```yaml
----
# Source: nextcloud/charts/mariadb/templates/secureconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mariadb
  labels:
    helm.sh/chart: mariadb-0.2.5
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "10.5.8"
    app.kubernetes.io/managed-by: Helm
stringData:
  MYSQL_ROOT_PASSWORD: H7G0J1RLFO
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_PASSWORD: G435eFYYnp
---
# Source: nextcloud/templates/secureconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  labels:
    helm.sh/chart: nextcloud-0.3.8
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "20.0.4-apache"
    app.kubernetes.io/managed-by: Helm
stringData:
  MYSQL_HOST: nextcloud-mariadb
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_PASSWORD:
---
```
And the database connection will fail, since nextcloud will attempt to log with an empty password.
