### ISSUE TITLE
Installing Commento Issue - Self Hosted Postgres

### ISSUE THREAD

**Issue by jotcodeofficial** [groundhog2k/helm-charts#560]
I have some trouble connecting my postgres database from my commento deployment. It is in another namespace.

`database_connect.go:20 dbConnect(): opening connection to postgres: mongodb://[database-user-name]:redacted@postgres-postgresql.databases:5432/[default-database-name]?sslmode=disable
`
`database_connect.go:31 dbConnect(): cannot talk to postgres, retrying in 10 seconds (4 attempts left): dial tcp 127.0.0.1:5432: connect: connection refused`

and on and on refusing.

The database table [default-database-name] lives in the databases namespace in a server called postgres.
I have a pgadmin deployment in that same namespace and I can log into the server with permissions I created for that server.

Inside the server I created a database, and created a user for it.

This users details are what I supply for my deployments database credentials in the values file.

For the database host value in the values file for the deployment i’ve tried both:

**postgres-postgresql.databases.svc.cluster.local**
and
**postgres-postgresql.databases**
```

## External database settings (is used when postgres.enabled is false <= I checked and it is false)
externalDatabase:
  ## Name of the database (default: [default-database-name])
  name:[default-database-name]

  ## Database user
  user: [database-user-name]

  ## Database password
  password: [this is set using the —set in the build script, works as tested with other variables]

  ## Database host
  host: postgres-postgresql.databases
  # old attemp host: postgres-postgresql.databases.svc.cluster.local

  ## Database port (default: 5432)
  port: 5432
```

Inside the properties panel for the server:

the server is called ‘postgres’. The service and deployment is called 'postgres-postgresql'
in the properties it says:

host: postgres-postgresql.databases.svc.cluster.local
port: 5432
username: [server-username]

In the settings for the database user that I created, it says can login? and that is set to true. 

hopefully you can help!
