### ISSUE TITLE
Commento Origin

### ISSUE THREAD

**Issue by jotcodeofficial** [groundhog2k/helm-charts#569]
When I deployed commento and I described the replica-set:

```

   Environment:
      COMMENTO_FORBID_NEW_OWNERS:  false
      COMMENTO_GZIP_STATIC:        true
      COMMENTO_PORT:               8080
      COMMENTO_ORIGIN:             https://%!s(<nil>)
      COMMENTO_SMTP_HOST:          <host-looks-ok>
      COMMENTO_SMTP_PORT:          465
      COMMENTO_SMTP_FROM_ADDRESS:  <from-address-looks-ok>
```

All of the fields look fine except for the COMMENTO_ORIGIN field.
This field is missing from the values.yml file, and seems to be present in other implementations of commento.
Did you forget it, or is this something that can be added via the interface after installation?
I assume it is just the domain where the installation will be present?

Thanks!

**Comment by groundhog2k** [comment]
Hi, the COMMENTO_ORIGIN field is set automatically based on the .Values.settings.protocol and .Values.ingress.host
You can see it in templates/_helpers.tpl.
Please give me feedback if this is not suitable for you. I'm sure we can find an alternative solution.

**Comment by jotcodeofficial** [comment]
I manage my own ingress in separate files for my deployments. 
And they just point to the relevant service:

Here is a small snippet from my ingress file:
```

  routes:
    - match: Host(`comments.domain.com`)
      kind: Rule
      services:
        - name: commento
          namespace: comments
          port: 80
```

So it would be better for me to be able to set the commento origin manually, perhaps have it in the values.yml file to let me and others override it?

example:
```

settings:
  ## Protocol for generated links (default: https)
  protocol: https

  ## Forbid new owners
  forbidNewOwners: false
  
  ## Allow to set origin manually
  commentoOrigin: domain.com (in my case would be comments.domain.com)
```
