### ISSUE TITLE
Postgres - Not updating pg_hba.conf preventing external access

### ISSUE THREAD

**Issue by darktempla** [groundhog2k/helm-charts#635]
First and foremost thanks for an awesome chart its great that you are using the out of the box official image where most others roll their own custom image. I haven't check your other charts out as yet but will be sure to have a look.

Any help you can provide around this issue is appreciated.

### Issue Description

I was able to get up and running with you chart quickly however run into some troubles when trying to make a connection to the database either via the overlay network with pgadmin (web) install in the same namespace or by exposing the database via ingress and attempting to connect externally.

After some investigation and looking at the docker image docs they mention if you set `POSTGRES_HOST_AUTH_METHOD` to 'md5' (default in charts) and `POSTGRES_PASSWORD` then the following last entry is added to **pg_hba.conf** file allowing external access requiring a password.
https://hub.docker.com/_/postgres

```bash
host    replication     all             ::1/128                 trust

host all all all md5
```

I thought it might be an issue with this version of the docker image so I used this docker compose file to test and the image appears to do what it mentions.

```yaml
version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_PASSWORD: sup3rs3cr3t
```
I also tried to create a vanilla pod using this manifest and again it worked as advertised.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
spec:
  containers:
    - name: pg
      image: postgres:13.4
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: md5
        - name: POSTGRES_PASSWORD
          value: sup3rs3cr3t
      ports:
        - name: db
          containerPort: 5432
          protocol: TCP
```

This leads me to believe something you are doing in your chart is causing some issues with the initialization script it is also possible its my configuration so I have included my values.yaml below for you to replicate.

### Steps to Reproduce
Use a k3d cluster as I use the local-path provisioner they provide.
https://k3d.io/v5.0.0/

**CHART VERSION** = 0.2.13

1. Run your postgres chart using the following values file (basically the default I have added EDITED comments to the values I changed)
```yaml 
## Default values for PostgreSQL deployment

## PostgreSQL docker image
image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

## Pull secrets and name override options
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## Optional service account
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Additional pod annotations
podAnnotations: {}

## Pod management policy
podManagementPolicy: OrderedReady

## Pod update strategy
updateStrategyType: RollingUpdate

## Pod security context uses file system group 999 (postgres)
podSecurityContext:
  fsGroup: 999

## Default security options to run PostgreSQL as non-root (postgres user), read only container without privilege escalation
securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsGroup: 999
  runAsUser: 999

## The postgres service configuration (Default is ClusterIP with port 5432)
service:
  type: ClusterIP
  port: 5432
  ## The node port (only relevant for type LoadBalancer or NodePort)
  nodePort:
  ## The cluster ip address (only relevant for type LoadBalancer or NodePort)
  clusterIP:
  ## The loadbalancer ip address (only relevant for type LoadBalancer)
  loadBalancerIP:

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Additional node selector
nodeSelector: {}

tolerations: []

affinity: {}

## Maximum number of revisions maintained in revision history
revisionHistoryLimit:

## Custom liveness probe (overwrites default liveness probe)
customLivenessProbe: {}

## Default health check
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 10

## Custom readiness probe (overwrites default readiness probe)
customReadinessProbe: {}

## Default readiness probe
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 10

## EDITED: Additional environment variables
env:
- name: "POSTGRES_PASSWORD"
  value: "sup3rs3cr3t"

## Arguments for the container entrypoint process
args: []

## Database configuration
settings:
  ## EDITED: The superuser password (default: a 10 char. alpahnumerical random password will be generated)
  superuserPassword: "sup3rs3cr3t"

  ## Postgres database authentication method (default: md5)
  authMethod: "md5"

  ## Optional init database arguments
  initDbArgs:

## Optional user database which is created during first startup with user and password
userDatabase: {}
  ## Name of the user database
  # name:

  ## Database user with full access rights
  # user:

  ## Password of the database user (default: a 10 char. alpahnumerical random password will be generated)
  # password:

## Optional custom configuration block that will be mounted as file in /etc/postgresql/postgresql.conf
customConfig: |-

## Storage parameters
storage:
  ##  Set persistentVolumenClaimName to reference an existing PVC
  persistentVolumeClaimName:

  ## EDITED: Alternative set requestedSize to define a size for a dynmaically created PVC
  requestedSize: 10Gi

  ## EDITED: the storage class name
  className: local-path

  ## Default access mode (ReadWriteOnce)
  accessModes:
    - ReadWriteOnce


```
2. Remote into the pod `kubectl exec -it <podname> -- sh`
3. Navigate to the data directory which for me is either `/var/lib/postgresql/data` or `/var/lib/postgresql/data/pg` for chart
4. Output the content of the pg_hba.conf file `cat pg_hba.conf`
5. Expected the `host all all all md5` to be appended to the bottom of the file its not for me.

This is the latest version of their init script  which may assist
https://github.com/docker-library/postgres/blob/master/13/bullseye/docker-entrypoint.sh

**Comment by groundhog2k** [comment]
Some of my other charts are using the postgres chart as dependency and I never had a problem with communication from one service to the postgres service.
Anyway, I used exactly the values.yaml you provided above with chart version 0.2.13 but had to change one line:
`className:`

I then deployed it on
a) local Docker tools with Kubernetes 1.21.4 on Windows with `className: hostpath`
b) my K8s cluster with Kubernetes 1.22 with NFS storage (using nfs-subdir-external-provisioner) with my own `className: nfs-storage`
and did exactly the steps 2. - 4.

This is the output I see for a) and also for b) at the end of the `/var/lib/postgresql/data/pg/pg_hba.conf` file:
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
```

Summarized: 
The file is looking like expected and I additionally did a succesful connection test to the service EP from another pod.
I can only guess what is going wrong in your case. Maybe it has to do with your storage provider.
Have you tried the helm chart with additional `userDatabase:` setting?
It will automatically execute a script and create a user database. If this fails I would guess something is not o.k. with storage (write protected? permissions?)

Alternative:
Try the helm chart completely without storage. ==> `storage: {}`
In this case it uses emptyDir. If pg_hba.conf is correct with this test then it's definetly caused by your storage provider.

**Comment by groundhog2k** [comment]
Another idea: As defined in the default `values.yaml` postgres is running without  root permissions using filesystem group and security context uid/gid 999 for better security. That could be also a difference between the chart and your test with a vanilla pod.
It's possible that the uid/gid has no permissions to the physical file system underneath `local-path`.

**Comment by darktempla** [comment]
@groundhog2k - thanks heaps for the prompt reply and suggestions.

After you suggested it I totally thought it may be a filesystem permission error however after `exec` into the postgres pod I could see that as you said the user and groups had been set correctly to 999 (postgres) even on the mounted PVC where the postgres data was stored. I was also as that user able to read, write to that volume no worries.

However during this process I did notice that I always ended up with a restart count of 1. As it turns out it was a race condition.

So the postgres script will only initialise the pod the first time when the volume is empty. After that it will just skip initialisation which makes sense it risks blowing away your persisted data (database), not ideal ;) This is what was showing up in the logs saying it had already run initialisation.

Looking at the events when the pod was starting was what uncovered the problem.
The readiness and liveliness probes you have defined by default were reporting errors and ended up restarting the pod (hence restart count of 1) before it could finish the initialisation process and because the PG_VERSION file was present the second time around the script assumed it had already been initialised. End result it never got run to completion and the entry in the **pg_hba.conf** file never written.

So I basically disabled your probes and I got zero restarts and the DB was initialised as expected 

I haven't had a chance yet but I will play around with the probe settings and adjust to something that works in my environment, I too am using network storage so suspect the speed of that causes the pod to start up a little slower than normal, its for a homelab so not too concerned about speed. 

Values file mod for troubleshooting issue:
```yaml
## Default health check
livenessProbe:
  enabled: true           # EDITED: very handy to have a toggle set to false for testing
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 10

## Custom readiness probe (overwrites default readiness probe)
customReadinessProbe: {}

## Default readiness probe
readinessProbe:
  enabled: false     # EDITED: very handy to have a toggle set to false for testing
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 10
```

Closing off this card.
Thanks again for your assistance hopefully one of these days our discussion in this issue helps someone else.
